"use client";

import { useState } from "react";
const formatNumber = (num: number) => new Intl.NumberFormat("en-US", { maximumFractionDigits: 2 }).format(num);
export default function DiscountCalculator() {
  const [originalPrice, setOriginalPrice] = useState<string>("");
  const [discountPercent, setDiscountPercent] = useState<string>("");
  const price = parseFloat(originalPrice); const discount = parseFloat(discountPercent);
  const isValid = !isNaN(price) && price > 0 && !isNaN(discount) && discount >= 0 && discount <= 100;
  const discountAmount = isValid ? (price * discount) / 100 : null; const finalPrice = isValid ? price - discountAmount! : null;
  const loadExample = () => { setOriginalPrice("200"); setDiscountPercent("25"); }; const reset = () => { setOriginalPrice(""); setDiscountPercent(""); };
  return <div className="py-10 px-4"><div className="max-w-xl mx-auto bg-white rounded-3xl shadow-xl border border-blue-100 p-8"><h1 className="text-3xl font-bold text-gray-900 text-center mb-2">Discount Calculator</h1><p className="text-center text-gray-500 mb-8">Calculate discount amount, final price, and savings instantly.</p><div className="space-y-6"><div><label htmlFor="originalPrice" className="block text-sm font-semibold text-gray-700 mb-1">Original Price ($)</label><input id="originalPrice" type="number" inputMode="decimal" min="0" step="0.01" value={originalPrice} onChange={(e) => setOriginalPrice(e.target.value)} placeholder="e.g. 200" className="w-full px-4 py-3 border border-blue-200 rounded-xl text-lg text-gray-900 focus:outline-none focus:ring-2 focus:ring-blue-500 bg-blue-50/30" /></div><div><label htmlFor="discountPercent" className="block text-sm font-semibold text-gray-700 mb-1">Discount Percentage (%)</label><input id="discountPercent" type="number" inputMode="decimal" min="0" max="100" step="0.01" value={discountPercent} onChange={(e) => setDiscountPercent(e.target.value)} placeholder="e.g. 25" className="w-full px-4 py-3 border border-blue-200 rounded-xl text-lg text-gray-900 focus:outline-none focus:ring-2 focus:ring-blue-500 bg-blue-50/30" /></div><div className="flex gap-3 pt-2"><button onClick={loadExample} className="flex-1 px-4 py-3 bg-blue-600 text-white font-semibold rounded-xl hover:bg-blue-700 transition shadow-md shadow-blue-200">Load Example</button><button onClick={reset} className="flex-1 px-4 py-3 bg-white text-blue-700 font-semibold rounded-xl border border-blue-300 hover:bg-blue-50 transition">Reset</button></div></div>{isValid && <div className="mt-8 bg-gradient-to-r from-blue-50 to-cyan-50 p-6 rounded-2xl border border-blue-100"><h2 className="text-xl font-bold text-gray-800 mb-4">Results</h2><div className="space-y-4"><div className="flex items-center justify-between"><span className="text-gray-600 font-medium">Discount Amount</span><span className="text-2xl font-bold text-blue-600">${formatNumber(discountAmount!)}</span></div><div className="flex items-center justify-between"><span className="text-gray-600 font-medium">Final Price</span><span className="text-2xl font-bold text-green-600">${formatNumber(finalPrice!)}</span></div><div className="flex items-center justify-between"><span className="text-gray-600 font-medium">You Save</span><span className="text-2xl font-bold text-purple-600">${formatNumber(discountAmount!)}</span></div></div></div>}</div></div>;
}
