"use client";
import { useState } from "react";
const formatNumber = (num: number) => new Intl.NumberFormat("en-US", { maximumFractionDigits: 2 }).format(num);
export default function CommissionCalculator() {
  const [baseAmount, setBaseAmount] = useState<string>(""); const [commissionPercent, setCommissionPercent] = useState<string>("");
  const base = parseFloat(baseAmount); const percent = parseFloat(commissionPercent); const isValid = !isNaN(base) && base > 0 && !isNaN(percent) && percent >= 0;
  const commissionAmount = isValid ? (base * percent) / 100 : null; const totalEarnings = isValid ? base + commissionAmount! : null;
  const loadExample = () => { setBaseAmount("1000"); setCommissionPercent("10"); }; const reset = () => { setBaseAmount(""); setCommissionPercent(""); };
  return <div className="py-10 px-4"><div className="max-w-xl mx-auto bg-white rounded-3xl shadow-xl border border-blue-100 p-8"><h1 className="text-3xl font-bold text-gray-900 text-center mb-2">Commission Calculator</h1><p className="text-center text-gray-500 mb-8">Calculate commission amount and total earnings instantly.</p><div className="space-y-6"><div><label htmlFor="baseAmount" className="block text-sm font-semibold text-gray-700 mb-1">Base Amount ($)</label><input id="baseAmount" type="number" inputMode="decimal" min="0" step="0.01" value={baseAmount} onChange={(e) => setBaseAmount(e.target.value)} placeholder="e.g. 1000" className="w-full px-4 py-3 border border-blue-200 rounded-xl text-lg text-gray-900 focus:outline-none focus:ring-2 focus:ring-blue-500 bg-blue-50/30" /></div><div><label htmlFor="commissionPercent" className="block text-sm font-semibold text-gray-700 mb-1">Commission Percentage (%)</label><input id="commissionPercent" type="number" inputMode="decimal" min="0" step="0.01" value={commissionPercent} onChange={(e) => setCommissionPercent(e.target.value)} placeholder="e.g. 10" className="w-full px-4 py-3 border border-blue-200 rounded-xl text-lg text-gray-900 focus:outline-none focus:ring-2 focus:ring-blue-500 bg-blue-50/30" /></div><div className="flex gap-3 pt-2"><button onClick={loadExample} className="flex-1 px-4 py-3 bg-blue-600 text-white font-semibold rounded-xl hover:bg-blue-700 transition shadow-md shadow-blue-200">Load Example</button><button onClick={reset} className="flex-1 px-4 py-3 bg-white text-blue-700 font-semibold rounded-xl border border-blue-300 hover:bg-blue-50 transition">Reset</button></div></div>{isValid && <div className="mt-8 bg-gradient-to-r from-blue-50 to-cyan-50 p-6 rounded-2xl border border-blue-100"><h2 className="text-xl font-bold text-gray-800 mb-4">Results</h2><div className="space-y-4"><div className="flex items-center justify-between"><span className="text-gray-600 font-medium">Commission Amount</span><span className="text-2xl font-bold text-blue-600">${formatNumber(commissionAmount!)}</span></div><div className="flex items-center justify-between"><span className="text-gray-600 font-medium">Total Earnings</span><span className="text-2xl font-bold text-green-600">${formatNumber(totalEarnings!)}</span></div></div></div>}</div></div>;
}
