"use client";

import { useMemo, useState } from "react";

type Calc = { slug: string; title: string; description: string; fields: { key: string; label: string; defaultValue: number }[]; formula: (v: Record<string, number>) => number; suffix?: string };

const configs: Record<string, Calc> = {
  "sales-tax-calculator":{slug:"sales-tax-calculator",title:"Sales Tax Calculator",description:"Calculate tax amount and total sale price.",fields:[{key:"price",label:"Price",defaultValue:100},{key:"tax",label:"Tax rate (%)",defaultValue:10}],formula:v=>v.price*v.tax/100,suffix:" tax"},
  "tip-calculator":{slug:"tip-calculator",title:"Tip Calculator",description:"Calculate a restaurant tip and total bill.",fields:[{key:"bill",label:"Bill",defaultValue:100},{key:"tip",label:"Tip rate (%)",defaultValue:15}],formula:v=>v.bill*v.tip/100,suffix:" tip"},
  "percentage-calculator":{slug:"percentage-calculator",title:"Percentage Calculator",description:"Find a percentage of a number.",fields:[{key:"number",label:"Number",defaultValue:100},{key:"percent",label:"Percentage (%)",defaultValue:20}],formula:v=>v.number*v.percent/100},
  "percent-change-calculator":{slug:"percent-change-calculator",title:"Percent Change Calculator",description:"Calculate percentage increase or decrease.",fields:[{key:"old",label:"Original value",defaultValue:100},{key:"new",label:"New value",defaultValue:125}],formula:v=>((v.new-v.old)/v.old)*100,suffix:"%"},
  "average-calculator":{slug:"average-calculator",title:"Average Calculator",description:"Calculate the arithmetic mean of values.",fields:[{key:"a",label:"Value 1",defaultValue:10},{key:"b",label:"Value 2",defaultValue:20},{key:"c",label:"Value 3",defaultValue:30}],formula:v=>(v.a+v.b+v.c)/3},
  "simple-interest-calculator":{slug:"simple-interest-calculator",title:"Simple Interest Calculator",description:"Calculate simple interest and total amount.",fields:[{key:"p",label:"Principal",defaultValue:1000},{key:"r",label:"Rate (%)",defaultValue:5},{key:"t",label:"Time (years)",defaultValue:2}],formula:v=>v.p*v.r*v.t/100},
  "compound-interest-calculator":{slug:"compound-interest-calculator",title:"Compound Interest Calculator",description:"Estimate compound interest growth.",fields:[{key:"p",label:"Principal",defaultValue:1000},{key:"r",label:"Annual rate (%)",defaultValue:5},{key:"t",label:"Years",defaultValue:5}],formula:v=>v.p*Math.pow(1+v.r/100,v.t)-v.p},
  "future-value-calculator":{slug:"future-value-calculator",title:"Future Value Calculator",description:"Calculate the future value of an investment.",fields:[{key:"p",label:"Present value",defaultValue:1000},{key:"r",label:"Rate (%)",defaultValue:6},{key:"t",label:"Years",defaultValue:5}],formula:v=>v.p*Math.pow(1+v.r/100,v.t)},
  "present-value-calculator":{slug:"present-value-calculator",title:"Present Value Calculator",description:"Discount a future amount to today's value.",fields:[{key:"fv",label:"Future value",defaultValue:1500},{key:"r",label:"Rate (%)",defaultValue:5},{key:"t",label:"Years",defaultValue:5}],formula:v=>v.fv/Math.pow(1+v.r/100,v.t)},
  "savings-calculator":{slug:"savings-calculator",title:"Savings Calculator",description:"Estimate savings growth with regular deposits.",fields:[{key:"start",label:"Starting savings",defaultValue:1000},{key:"monthly",label:"Monthly deposit",defaultValue:200},{key:"months",label:"Months",defaultValue:12}],formula:v=>v.start+v.monthly*v.months},
  "mortgage-calculator":{slug:"mortgage-calculator",title:"Mortgage Calculator",description:"Estimate monthly mortgage payments.",fields:[{key:"loan",label:"Loan amount",defaultValue:200000},{key:"rate",label:"Annual rate (%)",defaultValue:6},{key:"years",label:"Term (years)",defaultValue:30}],formula:v=>{const r=v.rate/1200,n=v.years*12;return r? v.loan*r*Math.pow(1+r,n)/(Math.pow(1+r,n)-1):v.loan/n}},
  "debt-to-income-calculator":{slug:"debt-to-income-calculator",title:"Debt-to-Income Calculator",description:"Calculate your debt-to-income ratio.",fields:[{key:"debt",label:"Monthly debt",defaultValue:1000},{key:"income",label:"Monthly gross income",defaultValue:5000}],formula:v=>v.debt/v.income*100,suffix:"%"},
  "commission-rate-calculator":{slug:"commission-rate-calculator",title:"Commission Rate Calculator",description:"Calculate commission earned from a sale.",fields:[{key:"sale",label:"Sale amount",defaultValue:1000},{key:"rate",label:"Commission rate (%)",defaultValue:5}],formula:v=>v.sale*v.rate/100},
  "revenue-calculator":{slug:"revenue-calculator",title:"Revenue Calculator",description:"Calculate revenue from units and price.",fields:[{key:"units",label:"Units sold",defaultValue:100},{key:"price",label:"Price per unit",defaultValue:25}],formula:v=>v.units*v.price},
  "cost-per-unit-calculator":{slug:"cost-per-unit-calculator",title:"Cost Per Unit Calculator",description:"Calculate average cost per unit.",fields:[{key:"cost",label:"Total cost",defaultValue:5000},{key:"units",label:"Units",defaultValue:250}],formula:v=>v.cost/v.units},
  "gross-profit-calculator":{slug:"gross-profit-calculator",title:"Gross Profit Calculator",description:"Calculate gross profit from sales and cost of goods.",fields:[{key:"sales",label:"Sales",defaultValue:10000},{key:"cogs",label:"Cost of goods sold",defaultValue:6000}],formula:v=>v.sales-v.cogs},
  "gross-margin-calculator":{slug:"gross-margin-calculator",title:"Gross Margin Calculator",description:"Calculate gross profit margin.",fields:[{key:"sales",label:"Sales",defaultValue:10000},{key:"cogs",label:"COGS",defaultValue:6000}],formula:v=>(v.sales-v.cogs)/v.sales*100,suffix:"%"},
  "net-profit-calculator":{slug:"net-profit-calculator",title:"Net Profit Calculator",description:"Calculate net profit after expenses.",fields:[{key:"revenue",label:"Revenue",defaultValue:10000},{key:"expenses",label:"Expenses",defaultValue:7000}],formula:v=>v.revenue-v.expenses},
  "net-margin-calculator":{slug:"net-margin-calculator",title:"Net Margin Calculator",description:"Calculate net profit margin.",fields:[{key:"profit",label:"Net profit",defaultValue:3000},{key:"revenue",label:"Revenue",defaultValue:10000}],formula:v=>v.profit/v.revenue*100,suffix:"%"},
  "operating-margin-calculator":{slug:"operating-margin-calculator",title:"Operating Margin Calculator",description:"Calculate operating profit margin.",fields:[{key:"operating",label:"Operating profit",defaultValue:2000},{key:"revenue",label:"Revenue",defaultValue:10000}],formula:v=>v.operating/v.revenue*100,suffix:"%"},
  "ebitda-calculator":{slug:"ebitda-calculator",title:"EBITDA Calculator",description:"Calculate earnings before interest, taxes, depreciation and amortization.",fields:[{key:"net",label:"Net income",defaultValue:5000},{key:"interest",label:"Interest",defaultValue:500},{key:"tax",label:"Taxes",defaultValue:800}],formula:v=>v.net+v.interest+v.tax},
  "cash-flow-calculator":{slug:"cash-flow-calculator",title:"Cash Flow Calculator",description:"Calculate net cash flow.",fields:[{key:"inflow",label:"Cash inflows",defaultValue:10000},{key:"outflow",label:"Cash outflows",defaultValue:7500}],formula:v=>v.inflow-v.outflow},
  "roi-percentage-calculator":{slug:"roi-percentage-calculator",title:"ROI Percentage Calculator",description:"Calculate return on investment as a percentage.",fields:[{key:"gain",label:"Net gain",defaultValue:2500},{key:"cost",label:"Investment cost",defaultValue:10000}],formula:v=>v.gain/v.cost*100,suffix:"%"},
  "break-even-units-calculator":{slug:"break-even-units-calculator",title:"Break-Even Units Calculator",description:"Find units required to break even.",fields:[{key:"fixed",label:"Fixed costs",defaultValue:5000},{key:"price",label:"Selling price per unit",defaultValue:50},{key:"variable",label:"Variable cost per unit",defaultValue:30}],formula:v=>v.fixed/(v.price-v.variable)},
  "markup-percentage-calculator":{slug:"markup-percentage-calculator",title:"Markup Percentage Calculator",description:"Calculate markup over cost.",fields:[{key:"price",label:"Selling price",defaultValue:150},{key:"cost",label:"Cost",defaultValue:100}],formula:v=>(v.price-v.cost)/v.cost*100,suffix:"%"},
  "price-after-discount-calculator":{slug:"price-after-discount-calculator",title:"Price After Discount Calculator",description:"Calculate the final price after a discount.",fields:[{key:"price",label:"Original price",defaultValue:100},{key:"discount",label:"Discount (%)",defaultValue:20}],formula:v=>v.price*(1-v.discount/100)},
  "vat-calculator":{slug:"vat-calculator",title:"VAT Calculator",description:"Calculate VAT amount and price including VAT.",fields:[{key:"net",label:"Net price",defaultValue:100},{key:"vat",label:"VAT rate (%)",defaultValue:15}],formula:v=>v.net*v.vat/100},
  "sales-growth-calculator":{slug:"sales-growth-calculator",title:"Sales Growth Calculator",description:"Calculate sales growth percentage.",fields:[{key:"previous",label:"Previous sales",defaultValue:10000},{key:"current",label:"Current sales",defaultValue:12000}],formula:v=>(v.current-v.previous)/v.previous*100,suffix:"%"},
  "customer-acquisition-cost-calculator":{slug:"customer-acquisition-cost-calculator",title:"Customer Acquisition Cost Calculator",description:"Calculate average cost to acquire a customer.",fields:[{key:"marketing",label:"Marketing spend",defaultValue:5000},{key:"customers",label:"New customers",defaultValue:100}],formula:v=>v.marketing/v.customers},
  "customer-lifetime-value-calculator":{slug:"customer-lifetime-value-calculator",title:"Customer Lifetime Value Calculator",description:"Estimate customer lifetime value.",fields:[{key:"order",label:"Average order value",defaultValue:50},{key:"orders",label:"Orders per year",defaultValue:6},{key:"years",label:"Customer years",defaultValue:3}],formula:v=>v.order*v.orders*v.years},
  "inventory-turnover-calculator":{slug:"inventory-turnover-calculator",title:"Inventory Turnover Calculator",description:"Calculate inventory turnover ratio.",fields:[{key:"cogs",label:"COGS",defaultValue:50000},{key:"inventory",label:"Average inventory",defaultValue:10000}],formula:v=>v.cogs/v.inventory},
  "days-sales-inventory-calculator":{slug:"days-sales-inventory-calculator",title:"Days Sales Inventory Calculator",description:"Estimate average days inventory is held.",fields:[{key:"inventory",label:"Average inventory",defaultValue:10000},{key:"cogs",label:"COGS",defaultValue:50000}],formula:v=>v.inventory/v.cogs*365,suffix:" days"},
  "payroll-tax-calculator":{slug:"payroll-tax-calculator",title:"Payroll Tax Calculator",description:"Estimate payroll tax from gross wages.",fields:[{key:"wages",label:"Gross wages",defaultValue:5000},{key:"rate",label:"Tax rate (%)",defaultValue:10}],formula:v=>v.wages*v.rate/100},
  "hourly-to-salary-calculator":{slug:"hourly-to-salary-calculator",title:"Hourly to Salary Calculator",description:"Convert hourly pay to an annual salary estimate.",fields:[{key:"hourly",label:"Hourly rate",defaultValue:20},{key:"hours",label:"Hours per week",defaultValue:40},{key:"weeks",label:"Weeks per year",defaultValue:52}],formula:v=>v.hourly*v.hours*v.weeks},
  "salary-to-hourly-calculator":{slug:"salary-to-hourly-calculator",title:"Salary to Hourly Calculator",description:"Convert annual salary to an hourly estimate.",fields:[{key:"salary",label:"Annual salary",defaultValue:52000},{key:"hours",label:"Hours per week",defaultValue:40},{key:"weeks",label:"Weeks per year",defaultValue:52}],formula:v=>v.salary/(v.hours*v.weeks)},
  "overtime-pay-calculator":{slug:"overtime-pay-calculator",title:"Overtime Pay Calculator",description:"Calculate overtime earnings.",fields:[{key:"hourly",label:"Hourly rate",defaultValue:20},{key:"hours",label:"Overtime hours",defaultValue:10},{key:"multiplier",label:"Overtime multiplier",defaultValue:1.5}],formula:v=>v.hourly*v.hours*v.multiplier},
  "loan-interest-calculator":{slug:"loan-interest-calculator",title:"Loan Interest Calculator",description:"Estimate simple loan interest.",fields:[{key:"principal",label:"Loan principal",defaultValue:10000},{key:"rate",label:"Annual rate (%)",defaultValue:8},{key:"years",label:"Years",defaultValue:3}],formula:v=>v.principal*v.rate/100*v.years},
  "savings-rate-calculator":{slug:"savings-rate-calculator",title:"Savings Rate Calculator",description:"Calculate the percentage of income saved.",fields:[{key:"saved",label:"Amount saved",defaultValue:1000},{key:"income",label:"Income",defaultValue:5000}],formula:v=>v.saved/v.income*100,suffix:"%"},
  "business-growth-calculator":{slug:"business-growth-calculator",title:"Business Growth Calculator",description:"Calculate compound business growth.",fields:[{key:"start",label:"Starting revenue",defaultValue:10000},{key:"growth",label:"Annual growth (%)",defaultValue:10},{key:"years",label:"Years",defaultValue:3}],formula:v=>v.start*Math.pow(1+v.growth/100,v.years)},
  "price-increase-calculator":{slug:"price-increase-calculator",title:"Price Increase Calculator",description:"Calculate a new price after an increase.",fields:[{key:"price",label:"Current price",defaultValue:100},{key:"increase",label:"Increase (%)",defaultValue:10}],formula:v=>v.price*(1+v.increase/100)},
};

export default function BusinessCalculator({ slug }: { slug: string }) {
  const c=configs[slug];
  const [values,setValues]=useState<Record<string,number>>(()=>Object.fromEntries(c.fields.map(f=>[f.key,f.defaultValue])));
  const result=useMemo(()=>c.formula(values),[c,values]);
  const related=Object.values(configs).filter(x=>x.slug!==slug).slice(0,6);
  return <main style={{maxWidth:800,margin:"0 auto",padding:"32px 20px",fontFamily:"system-ui",lineHeight:1.6}}>
    <nav aria-label="Breadcrumb" style={{marginBottom:20}}><a href="/">BizToolkit</a> <span aria-hidden="true">›</span> <span>{c.title}</span></nav>
    <div style={{minHeight:90,border:"1px dashed #bbb",borderRadius:10,display:"grid",placeItems:"center",marginBottom:24,fontSize:13,color:"#777"}} aria-label="Advertisement">Advertisement</div>
    <h1>{c.title}</h1><p>{c.description}</p>
    <section style={{display:"grid",gap:16,marginTop:28}}>{c.fields.map(f=><label key={f.key} style={{display:"grid",gap:7}}>{f.label}<input type="number" value={values[f.key]} onChange={e=>setValues({...values,[f.key]:Number(e.target.value)})} style={{padding:12,border:"1px solid #ccc",borderRadius:8,fontSize:16}} /></label>)}</section>
    <div style={{marginTop:28,padding:20,border:"1px solid #ddd",borderRadius:12}}><strong>Result</strong><div style={{fontSize:32,fontWeight:700,marginTop:8}}>{Number.isFinite(result)?result.toLocaleString(undefined,{maximumFractionDigits:2}):"—"}{c.suffix||""}</div></div>
    <div style={{minHeight:90,border:"1px dashed #bbb",borderRadius:10,display:"grid",placeItems:"center",margin:"28px 0",fontSize:13,color:"#777"}} aria-label="Advertisement">Advertisement</div>
    <section aria-labelledby="related-calculators"><h2 id="related-calculators">Related Calculators</h2><div style={{display:"grid",gap:8}}>{related.map(x=><a key={x.slug} href={`/${x.slug}`}>{x.title}</a>)}</div></section>
    <footer style={{marginTop:32,paddingTop:16,borderTop:"1px solid #eee"}}><a href="/">← Back to BizToolkit</a></footer>
  </main>;
}
